# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 최재송
title: NodeJs & TypeScript 백엔드 개발자
email: cjs5241@gmail.com
phone: 010-3138-1106

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: cjs1301

# Additional icon links
# additional_links:
#     - title: itsgoingto.be
#       icon: fas fa-globe
#       url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "G-6CKKGMRTHC"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
    웹/앱 서비스 백엔드 개발과 스타트업 개발자로서의 다양한 경험이 있습니다.  
    Node.js, MySQL, Redis, AWS, Git, Linux 등을 사용하여 프로덕션 서비스를 설계, 개발, 운영한 경험으로  
    확장성과 유지 보수성이 높은 백엔드 아키텍처와 패턴을 위해 언제나 고민하고 있습니다.  
      
    서비스 개발이란 결국 개발과 비즈니스와의 <mark>커뮤니케이션</mark>이 가장 중요하다고 생각하고 있습니다.  
    능동적이고 적극적인 커뮤니케이션으로 문제 해결과 비즈니스 발전을 위해 뛰어듭니다.  
    이러한 점을 바탕으로 더 좋은 개발자로서 성장하기 위해 더 치열하게 학습하고, 경험하고, 노력하고 있습니다.

content:
    - title: Skill
      layout: list
      content:
          - layout: left
            title: Backend
            description: | # this will include new lines to allow paragraphs
                * NodeJS (TypeScript)
                * NestJS, Express
                * TypeORM, Sequelize, Mongoose
                * Jest, Swagger
                * IntelliJ, Visual Studio Code
          - layout: left
            title: DevOps
            description: | # this will include new lines to allow paragraphs
                * MySQL, MariaDB, PostgreSQL
                * Github Action, AWS Code Deploy
                * Serverless, ECS, Lambda@Edge, Elastic Cache (Redis), RDS (Aurora), S3, EC2, Cloud Watch
                * Nginx
                * Linux Ubuntu

    - title: Experience # Title for the section
      layout: list # Type of content section (list/text)
      content:
          - layout: left
            title: 모라니크
            link: https://app.moranique.com
            # link_text: boringcompany.com
            sub_title: 제품팀 | 백엔드 개발자
            caption: 2022.03 - Present
            quote: >
                mau 16만, 50~60 중년여성 패션이커머스
            description: | # this will include new lines to allow paragraphs
                - Github Action CI/CD 자동화
                - Strapi CMS 운영
                - Express -> NestJs / Serverless -> ECS/Docker 이전
                - PostMan 유료 -> Swagger 이전
                - 취소 / 반품 / 교환 개발
          - layout: left
            title: 노트하우
            link: https://www.daehaktutor.com/
            # link_text: boringcompany.com
            sub_title: 백엔드 개발자
            caption: 2022.01 - 2022.03
            quote: >
                대학 스터디 올인원 서비스
            description: | # this will include new lines to allow paragraphs
                - 대학생 인증 시스템 개발
                - 서버리스 이전 AWS 비용 50%감소
                - ELK 구축
          - layout: left
            title: 오픈메타
            link: https://www.openmeta.city
            # link_text: boringcompany.com
            sub_title: 백엔드 개발자
            caption: 2021.08 - 2022.01
            quote: >
                NFT 기반 가상 부동산 서비스
            description: | # this will include new lines to allow paragraphs
                - NFT 부동산 메타버스 (백엔드 100%)
                - 마을이야기 페이 : 앱,관리자 페이지 서버개발(광진구 결제앱) (백엔드 100%)
          - layout: left
            title: Whywine
            link: https://www.whywine.co.kr
            # link_text: boringcompany.com
            sub_title: 코드스테이츠 파이널 프로젝트 (4인 / 4주) | 백엔드 개발자(팀장)
            caption: 2021.04 - 2021.06
            quote: >
                (호스팅 종료) 당신의 취향에 맞는 최고의 와인을 추천해드립니다.
            description: | # this will include new lines to allow paragraphs
                - 초기 서버셋팅, Nginx https 셋팅
                - passport 인증시스템 개발
                - bcrypt를 사용한 회원정보 암호화 저장, 관리
                - 회원 API 개발
                - 프로젝트 최종 배포 및 배포관리

    # - title: Projects # Title for the section
    #   layout: list # Type of content section (list/text)
    #   content:
    #       - layout: top-middle
    #         title: 모라니크 인프라 운영
    #         link: github.com/sproogen
    #         link_text: Project Website
    #         additional_links:
    #             - title: sproogen/modern-resume-theme
    #               icon: fab fa-github
    #               url: github.com/sproogen/modern-resume-theme
    #             # - title: Github page for project (eg. sproogen/modern-resume-theme)
    #             #   icon: fab fa-github
    #             #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
    #         quote: >
    #             This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
    #         description: | # this will include new lines to allow paragraphs
    #             I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

    - title: Education # Title for the section
      layout: list # Type of content section (list/text)
      content:
          - layout: left
            title: 인프런
            caption: 2021 -
            sub_title: BSc Computer Science
            quote: >

            description: | # this will include new lines to allow paragraphs
                - 호돌맨 호돌맨의 요절복통 개발쇼 (SpringBoot, Vue.JS, AWS)
                - 윤상석 탄탄한 백엔드 NestJS, 기초부터 심화까지
                - 김영한 스프링 MVC 1편 - 백엔드 웹 개발 핵심 기술
                - 김영한 스프링 핵심 원리 - 고급편
                - 김영한 스프링 핵심 원리 - 기본편 등
          - layout: left
            title: F-Lab
            caption: 2022.03 - 2022.05
            sub_title: Java BackEnd 멘토링
            quote: >

            description: | # this will include new lines to allow paragraphs
                - 시니어 개발자들의 전문 학습방향 멘토링 서비스
          - layout: left
            title: 메가존아이티
            caption: 2021.03 - 2022.03
            sub_title: 컴퓨터공학과(4년제 학점은행제)
            quote: >

            description: | # this will include new lines to allow paragraphs
                - 수강한 과목  
                네트워크, 데이터베이스, 시스템프로그래밍, 알고리즘,  
                운영체제, 인공지능, 자료구조, 전자계산기 구조,  
                C언어, 마이크로프로세서, 소프트웨어공학, 시스템분석설계,   
                인터넷보안, 정보통신개론, 컴퓨터시스템
          - layout: left
            title: 코드스테이츠
            caption: 2021.01 - 2021.06
            sub_title: Advanced software engineering, Immersive program (27기 수료)
            quote: >

            description: | # this will include new lines to allow paragraphs
                - Javascript 기반 Full-stack 과정(React, NodeJS, AWS 등)
                - 자료 구조, 알고리즘, 인증, 배포
                - Git work flow
                - 페어 프로그래밍, 2번의 팀 프로젝트 진행

    # - title: A Little More About Me
    #   layout: text
    #   content: | # this will include new lines to allow paragraphs
    #       Alongside my interests in networks and software engineering some of my other interests and hobbies are:
    #       - Rock climbing
    #       - Gaming
    #       - Knitting
    #       - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

    #       Look at this cool image
    #       ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
    sass_dir: _sass
    style: compressed

plugins:
    - jekyll-seo-tag
