# Site
repository: sproogen/resume-theme
favicon: images/JS.jpeg

# Content configuration version
version: 2

# Personal info
name: 최재송
title: NodeJs & TypeScript 백엔드 개발자
email: cjs5241@gmail.com
phone: 010-3138-1106
website: https://cjs1301.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: cjs1301

# Additional icon links
# additional_links:
#     - title: itsgoingto.be
#       icon: fas fa-globe
#       url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "G-6CKKGMRTHC"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
    웹/앱 서비스 백엔드 개발과 스타트업 개발자로서의 다양한 경험이 있습니다.  
       
    NodeJs & TypeScript, AWS 중심으로 프로덕션 서비스를 설계, 개발, 운영한 경험으로  
       
    <mark>확장성</mark>과 <mark>유지 보수성</mark>이 높은 백엔드 아키텍처와 패턴을 위해 언제나 고민하고 있습니다.  
       
    서비스 개발이란 결국 개발과 비즈니스와의<mark>커뮤니케이션</mark>이 가장 중요하다고 생각하고 있습니다.  
       
    이러한 점을 바탕으로 더 좋은 개발자로서 성장하기 위해 학습하고, 경험하고, 노력하고 있습니다.

content:
    - title: Skill
      layout: list
      content:
          - layout: left
            title: Backend
            description: | # this will include new lines to allow paragraphs
                * NodeJS (TypeScript)
                * NestJS, Express
                * TypeORM, Sequelize, Mongoose
                * Jest, Swagger
                * IntelliJ, Visual Studio Code
          - layout: left
            title: DevOps
            description: | # this will include new lines to allow paragraphs
                * MySQL, MariaDB, PostgreSQL
                * Github Action, AWS Code Deploy
                * Serverless, ECS, Lambda@Edge, Elastic Cache (Redis), RDS (Aurora), S3, EC2, Cloud Watch
                * Nginx
                * Linux Ubuntu

    - title: Experience # Title for the section
      layout: list # Type of content section (list/text)
      content:
          - layout: left
            title: 모라니크
            link: https://app.moranique.com
            # link_text: boringcompany.com
            sub_title: 제품팀 | 백엔드 개발자
            caption: 2022.03 - Present
            quote: >
                MAU 16만, 50~60 중년여성 패션이커머스
            description: | # this will include new lines to allow paragraphs
                - Github Action CI/CD 자동화
                - 인프라 운영
                - Express -> NestJs 도입
                - Lambda -> ECS/Fargate 이전
                - 취소 / 반품 / 교환 개발
          - layout: left
            title: 노트하우
            link: https://www.daehaktutor.com/
            # link_text: boringcompany.com
            sub_title: 백엔드 개발자
            caption: 2022.01 - 2022.03
            quote: >
                대학 스터디 올인원 서비스
            description: | # this will include new lines to allow paragraphs
                - 대학생 인증 시스템 개발
                - 서버리스 이전 AWS 비용 40%감소
                - ELK 구축(활용 실패)
          - layout: left
            title: 오픈메타
            link: https://www.openmeta.city
            # link_text: boringcompany.com
            sub_title: 백엔드 개발자
            caption: 2021.08 - 2022.01
            quote: >
                NFT 기반 가상 부동산 서비스
            description: | # this will include new lines to allow paragraphs
                - NFT 부동산 메타버스 (백엔드 100%)
                - 마을이야기 페이 : 앱,관리자 페이지 서버개발(광진구 결제앱) (백엔드 100%)

    - title: Projects # Title for the section
      layout: list # Type of content section (list/text)
      content:
          - layout: top-middle
            border: weak
            title: 스타트업 인프라 운영
            link: github.com/cjs1301/diagrams/blob/main/moranique_infra_architecture.pdf
            link_text: Architecture Diagram Link
            sub_title: 모라니크 (moranique)
            description: | # this will include new lines to allow paragraphs
                - 적은 인력으로 빠른 서비스 개발을 위해 Clayful(Saas)과 오픈 소스(Strapi, Retool, Redash, Airflow) 등으로 구성되어 있습니다.  
                - AWS data tranfer 비용 할인을 위해 베스핀글로벌을 도입하여 <mark>30% 요금을 절감</mark>
          - layout: top-middle
            border: weak
            title: Lambda -> ECS/Fargate 이전
            sub_title: 모라니크 (moranique)
            description: | # this will include new lines to allow paragraphs
                - Lambda 환경 이해의 어려움(로컬 개발환경과 배포환경을 일치 시키기 어려움)  
                - 러닝커브가 높은 yml 작성(이해없이 설정한 환경을 prod에서 쓰기엔 불안함)
          - layout: top-middle
            border: weak
            title: NestJs 도입
            sub_title: 모라니크 (moranique)
            description: | # this will include new lines to allow paragraphs
                - 잘활용되지 않는 Postman대신 api 문서를 코드화하여 문서작성시간을 감소하기 위한 목적(Swagger)  
                - 소단위로 쪼개어져 찾기 힘들었던 백엔드 소스코드들을 한곳에 모아 매번 이용되던 코드와 미들웨어등을 묶어서 쓰기위한 목적(OOP,AOP)  
                - 미숙한 테스트코드 작성을 좀더 편하게 작성해보기 위한 목적  
                - 호출단위로 요금이 부과되는 Clayful(Saas)의 캐싱처리를 위한 백엔드 소스코드 통합
          - layout: top-middle
            border: weak
            title: 취소 / 반품 / 교환 개발
            sub_title: 모라니크 (moranique)
            description: | # this will include new lines to allow paragraphs
                - Clayful(Saas)에서 제공하지 않던 교환기능 부재를 해결  
                - 엑셀 시트를 활용하여 주문 정산관리를 하고 있던 운영 일부 자동화
          - layout: top-middle
            border: weak
            title: 대학생 인증 시스템 개발
            sub_title: 노트하우 (knotehow)
            description: | # this will include new lines to allow paragraphs
                - 이메일 인증 개발  
                - 학생증 인증(구글비전으로 텍스트 DB화 및 회원정보 비교) 개발
          - layout: top-middle
            border: weak
            title: 서버리스 이전
            sub_title: 노트하우 (knotehow)
            description: | # this will include new lines to allow paragraphs
                - 트래픽이 낮아 Api 호출횟수가 너무 적은점을 활용  
                - ec2에서 lambda로 모두 이전
          - layout: top-middle
            border: weak
            title: 오픈메타 서비스 서버 개발
            link: openmeta.city
            link_text: Openmeta City Website Link
            sub_title: 오픈메타 (openmeta)
            description: | # this will include new lines to allow paragraphs
                - 공공데이터 크롤링 자동화  
                - 지번 기반 폴리곤 데이터 도로명 기준 폴리곤으로 변환  
                - 트래픽 처리를 위한 로드밸런싱 구축, 오토스케일링  
                - 소셜 로그인 개발  
                - 백엔드 기여도 100%
          - layout: top-middle
            border: weak
            title: 마을이야기 광진 페이 앱 서버 개발
            additional_links:
                - title: maelstory pay ios
                  icon: fab fa-app-store
                  url: https://apps.apple.com/kr/app/%EB%A7%88%EC%9D%84%EC%9D%B4%EC%95%BC%EA%B8%B0-%ED%8E%98%EC%9D%B4/id1597053678
                - title: maelstory pay android
                  icon: fab fa-android
                  url: https://play.google.com/store/apps/details?id=net.maeulstory.pay
            sub_title: 광진구 지역 결제 페이 앱
            description: | # this will include new lines to allow paragraphs
                - 기존 마을이야기 앱과 회원정보 연동 로그인 개발  
                - 결제 기능 개발  
                - 어드민 페이지 api 개발  
                - 백엔드 개발 기여도 100%
          - layout: top-middle
            title: WhyWine
            link: https://www.whywine.co.kr
            # link_text: boringcompany.com
            sub_title: 코드스테이츠 파이널 프로젝트 (4인 / 4주) | 백엔드 개발자(팀장)
            # caption: 2021.04 - 2021.06
            quote: >
                (호스팅 종료) 당신의 취향에 맞는 최고의 와인을 추천해드립니다.
            description: | # this will include new lines to allow paragraphs
                - 초기 서버셋팅, Nginx https 셋팅
                - passport 인증시스템 개발
                - bcrypt를 사용한 회원정보 암호화 저장, 관리
                - 회원 API 개발
                - 프로젝트 최종 배포 및 배포관리

    - title: Education # Title for the section
      layout: list # Type of content section (list/text)
      content:
          - layout: left
            title: 인프런
            caption: 2021 -
            sub_title:
            quote: >
                인터넷 개발 강의
            description: | # this will include new lines to allow paragraphs
                - 호돌맨 호돌맨의 요절복통 개발쇼 (SpringBoot, Vue.JS, AWS)
                - 윤상석 탄탄한 백엔드 NestJS, 기초부터 심화까지
                - 김영한 스프링 MVC 1편 - 백엔드 웹 개발 핵심 기술
                - 김영한 스프링 핵심 원리 - 고급편
                - 김영한 스프링 핵심 원리 - 기본편 등
          - layout: left
            title: F-Lab
            caption: 2022.03 - 2022.05
            sub_title: Java BackEnd 멘토링
            quote: >
                시니어 개발자들의 전문 학습방향 멘토링 서비스
            description: | # this will include new lines to allow paragraphs
                - Java, Spring 학습
                - 백엔드 아키텍처, TDD, OOP
          - layout: left
            title: 메가존아이티
            caption: 2021.03 - 2022.03
            sub_title: 컴퓨터공학과(4년제 학점은행제)
            quote: >

            description: | # this will include new lines to allow paragraphs
                - 수강한 과목  
                네트워크, 데이터베이스, 시스템프로그래밍, 알고리즘,  
                운영체제, 인공지능, 자료구조, 전자계산기 구조,  
                C언어, 마이크로프로세서, 소프트웨어공학, 시스템분석설계,   
                인터넷보안, 정보통신개론, 컴퓨터시스템
          - layout: left
            title: 코드스테이츠
            caption: 2021.01 - 2021.06
            sub_title: Advanced software engineering, Immersive program (27기 수료)
            quote: >

            description: | # this will include new lines to allow paragraphs
                - Javascript 기반 Full-stack 과정(React, NodeJS, AWS 등)
                - 자료 구조, 알고리즘, 인증, 배포
                - Git work flow
                - 페어 프로그래밍, 2번의 팀 프로젝트 진행

    # - title: PDF Resume
    #   layout: text
    #   content: | # this will include new lines to allow paragraphs
    #       이 이력서는 웹 페이지를 pdf로 변환한 이력서 입니다. 링크와 프로필 이미지를 보시려면 cjs1301.github.io로 방문 해주세요.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
    sass_dir: _sass
    style: compressed

plugins:
    - jekyll-seo-tag
